### ISSUE TITLE
Travis CI badge is broken

### ISSUE THREAD

**Issue by chip** [spicejs/spicejs#14]
@3den - Cool project! :+1:  

Is this repo private or public?  I was trying to submit a fix for this, but couldn't access it on Travis.  LMK if I can help.

**Comment by chip** [comment]
Hello!

Important message, visit http://apextenders.com/yourself.php?1u

Chip Castle

**Comment by 3den** [comment]
@chip i can't access that link

**Comment by luiztiago** [comment]
yourself.php? lol

**Comment by chip** [comment]
@3den, @luiztiago - Sorry for the trouble, guys. I've been hacked. :frowning:

**Comment by chip** [comment]
Hello!

 

New message, please read <http://tastetiger.com/art.php?1y>

 

Chip Castle

**Comment by chip** [comment]
Hey!

Open message http://nmgweb.net/tone.php?bdmrb

Chip Castle

**Comment by 3den** [comment]
lol @chip virus again!

**Comment by chip** [comment]
Thanks Marcelo, but I can't lol about this anymore. Sorry, but I don't know
how to prevent this from happening since they're spoofing the Return-Path
of these messages, acting as if they're me.

Thank you,

Chip Castle
http://chipcastle.com
chip@chipcastle.com (Email/Google Hangouts)
chipcastle (Skype)
850-225-0552 (Cell)

**Comment by 3den** [comment]
can't you just format ur hard drive ?

**Comment by chip** [comment]
I am considering that, but I don't think that's the real issue. When I
receive these spam messages in Gmail, I click "Show Original" to inspect
all of the email headers. They spoof the "Return-Path" and other mail
headers to make it appear as if it's coming from my address, but if you
look at the servers used, they're not coming from Google (my SMTP
provider). They have all of my contacts, so they just email everyone,
including these github addresses. The github ones won't show the headers,
though, unfortunately.

Thank you,

Chip Castle
http://chipcastle.com
chip@chipcastle.com (Email/Google Hangouts)
chipcastle (Skype)
850-225-0552 (Cell)

**Comment by chip** [comment]
Hey!

Open message http://mobile-machining-experience.eu/side.php?jq1lv

Chip Castle

**Comment by chip** [comment]
Hey!

Open message http://skinrefined.com/field.php?la

Chip Castle

**Comment by chip** [comment]
Hello! 

We've had an amazing  days out of town this  weekend,  just take a look at the place we've been to, here are some pictures  http://trycridespa.raovattoi.com/aejemd

Sent from my iPhone, Chip Castle

**Comment by chip** [comment]
Hello,

I was just wondering about your opinion on that stuff, please take a look and tell me what you think <http://kihocuhi.listnlp.com/aelfw>

Warmly, Chip Castle
